"""empty message

Revision ID: 203fe87aa739
Revises: 3fe68a5bd190
Create Date: 2024-03-01 18:48:28.579964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203fe87aa739'
down_revision = '3fe68a5bd190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
