"""empty message

Revision ID: 9e96da7f54df
Revises: 203fe87aa739
Create Date: 2024-03-06 01:11:42.833578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e96da7f54df'
down_revision = '203fe87aa739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('terms', sa.Boolean(), nullable=False))
        batch_op.drop_column('hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('terms')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
